# Test all applications concurrently using a build matrix (see
# https://docs.travis-ci.com/user/build-matrix/).
jobs:
  include:

    # Elixir
    - language: elixir
      elixir:
        - 1.11.3
      otp_release:
        - 23.2.4
      env:
        - MIX_ENV=test
      before_install:
        - cd elixir
      script:
        - mix do compile --warnings-as-errors, coveralls.json
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    # JavaScript
    - language: node_js
      node_js:
        - 14.15.5
      env:
        - NODE_ENV=test
      before_install:
        - cd javascript
      after_script:
        - npm run codecov

    # Node.js
    - language: node_js
      node_js:
        - 14.15.5
      env:
        - NODE_ENV=test
      before_install:
        - cd node
      after_script:
        - npm run codecov

    # PHP
    - language: php
      php:
        - 7.4.15
      env:
        XDEBUG_MODE: coverage
      before_script:
        - travis_retry composer self-update
        - cd php
        - travis_retry composer install --no-interaction
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml --whitelist src --whitelist tests tests
      after_script:
        - bash <(curl -s https://codecov.io/bash)

    # Ruby
    - language: ruby
      ruby:
        - 3.0.0
      before_install:
        - cd ruby
