# Test all applications concurrently using a build matrix (see
# https://docs.travis-ci.com/user/build-matrix/).
jobs:
  include:

    # Elixir
    - language: elixir
      elixir:
        - 1.10.4
      otp_release:
        - 23.0.2
      env:
        - MIX_ENV=test
      before_install:
        - cd elixir
      script:
        - mix do compile --warnings-as-errors, coveralls.json
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    # JavaScript
    - language: node_js
      node_js:
        - 14.5.0
      env:
        - NODE_ENV=test
      before_install:
        - cd javascript
      after_script:
        - npm run codecov

    # Node.js
    - language: node_js
      node_js:
        - 14.5.0
      env:
        - NODE_ENV=test
      before_install:
        - cd node
      after_script:
        - npm run codecov

    # Ruby
    - language: ruby
      ruby:
        - 2.7.1
      before_install:
        - cd ruby
