jobs:
  include:

    - language: node_js
      node_js:
        - 14
      before_install:
        - cd node
      after_script:
        - npm run codecov

    - language: ruby
      ruby:
        - 2.7
      before_install:
        - cd ruby
      before_script:
        - cp codecov.yml ..
